In [11]:
import numpy as np
import pandas as pd

In [14]:
data = pd.read_csv("data/med_rec_data.csv")
data.head()

Group Referral_Date Enrolled_Date First_in_home_visit    IHV_week  \
0  Intervention     17Jan2017     24Jan2017          01/24/2017  01/21/2017   
1       Control     24Mar2017     28Mar2017          03/28/2017  03/25/2017   
2  Intervention     10Mar2017     14Mar2017          03/14/2017  03/11/2017   
3  Intervention     28Jun2017     30Jun2017          06/30/2017  06/24/2017   
4     Alternate     10Mar2017     15Mar2017          03/15/2017  03/11/2017   

  Med_rec_visit_date                   CM referral_source  admit_date  \
0         01/24/2017  FAIRBANKS KATHERINE       Automated  12/16/2016   
1                NaN         ROGERS DEBRA       Automated  03/19/2017   
2         03/14/2017         WARREN BRETT          Manual  02/13/2017   
3         06/30/2017         WARREN BRETT       Automated  05/25/2017   
4                NaN  FAIRBANKS KATHERINE       Automated  03/05/2017   

  Discharge_Date                     ...                     CV_CHF DIABETES  \
0     01/13/2017                     ...                        1.0      1.0   
1     03/24/2017                     ...                        1.0      0.0   
2     03/09/2017                     ...                        0.0      0.0   
3     06/26/2017                     ...                        0.0      0.0   
4     03/09/2017                     ...                        0.0      1.0   

   RES_COPD  Readmit_MCC CURRENT_ZIP_CD  ER_Visit_date  PCP_Visit_date  \
0       0.0  RESPIRATORY        53402.0            NaN      02/07/2017   
1       0.0          NaN        66204.0     03/26/2017      04/20/2017   
2       0.0   INFECTIONS        64134.0     06/02/2017             NaN   
3       0.0          NaN        64134.0            NaN             NaN   
4       0.0          NaN        53213.0     04/03/2017      03/16/2017   

   Specialist_Visit_date                                    Admit_diag_desc  \
0             01/25/2017                                           WEAKNESS   
1             04/12/2017                         HEART FAILURE, UNSPECIFIED   
2                    NaN                   ESSENTIAL (PRIMARY) HYPERTENSION   
3                    NaN  POSTINFECTIOUS ACUTE NECROTIZING HEMORRHAGIC E...   
4             03/23/2017                                          BALANITIS   

                            Readmit_diag_desc  
0  PLEURAL EFFUSION, NOT ELSEWHERE CLASSIFIED  
1                                         NaN  
2                SEPSIS, UNSPECIFIED ORGANISM  
3                                         NaN  
4                                         NaN  

[5 rows x 36 columns]

In [35]:
data['score'].mean()

192.50644397685429

In [39]:
row = np.array([1, 2, 3, 4])
col = np.array([[10], [20], [30], [40]])
print(row+col)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
